version: '3.7'

volumes:
  go-orm-postgres:

services:
  postgres:
    image: postgres # use latest official postgres version
    env_file:
      - ./docker/postgres/database.env # configure postgres
    volumes:
      - "go-orm-postgres:/var/lib/postgresql/data/"
    ports:
      - "127.0.0.1:5433:5432"
    networks:
      - go-orm-network

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - go-orm-network


networks:
  go-orm-network:
    driver: bridge

